#!/bin/bash

# kill any Vice64 session in progress
killall x64 || true 

# extracting output file name
ARGUMENT="$1"

OUTPUT=$(awk '/\!to/' "$1" | sed 's/.*\/\(.*\)\".*/\1/')
BUILD_DIR=$(awk '/\!to/' "$ARGUMENT" | sed 's/.*"\(.*\)".*/\1/')
BUILD_DIR=$(dirname $BUILD_DIR)


if [ ! -n "$OUTPUT" ]; then
    echo "You have not specified an output file with the !to pseudo opcode in your index file"
    echo 'example:  !to "build/hello_world.prg",cbm'
    exit 1
fi


if [ ! -d "$BUILD_DIR" ] 
then
	echo "$BUILD_DIR does not exists - creating it."
    mkdir -p "$BUILD_DIR"
fi

# start compiling
echo "Compiling 6502 code with Input file $1 to $OUTPUT"
/usr/local/bin/acme "$1"

# crunch output prg file
echo "crunching $OUTPUT"
/usr/local/bin/pucrunch "$BUILD_DIR/$OUTPUT" "$BUILD_DIR/$OUTPUT" 

# run in emulator
echo "loading $PWD/../build/$OUTPUT"
/Applications/Vice64/x64.app/Contents/MacOS/x64 "$BUILD_DIR/$OUTPUT" &
